### ISSUE TITLE
Email regex doesn't match invalid email 

### ISSUE THREAD

**Issue by JoschuaGoetz** [Fridgify/Fridgify_Frontend#7]
The email 'email@-example.com' is invalid because the first part of the domain part is a dash. 
@DennisRein Should i fix it and ship the change with a merge when im finished or do you want to fix it ?

**Comment by DennisRein** [comment]
So the issue is that @-domain emails do get accepted right? If that's the guys I'd appreciate it if you could fix it quickly because I am working right now on other screens.

**Comment by JoschuaGoetz** [comment]
Okay, the issue isn't that important so i will ship the change when i merge into develop.

**Comment by JoschuaGoetz** [comment]
Fixed with 6c40f32bcc5f525c44738f10cdd19ca563555d9f
